<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251126171603 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE company (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by_id INT NOT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4FBF094FB03A8386 ON company (created_by_id)');
        $this->addSql('CREATE INDEX IDX_4FBF094F896DBBDE ON company (updated_by_id)');
        $this->addSql('CREATE TABLE job (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, company_id INT NOT NULL, created_by_id INT NOT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FBD8E0F8979B1AD6 ON job (company_id)');
        $this->addSql('CREATE INDEX IDX_FBD8E0F8B03A8386 ON job (created_by_id)');
        $this->addSql('CREATE INDEX IDX_FBD8E0F8896DBBDE ON job (updated_by_id)');
        $this->addSql('CREATE TABLE job_application (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, motivation_letter TEXT DEFAULT NULL, cv_filename VARCHAR(255) NOT NULL, status VARCHAR(255) DEFAULT \'submitted\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, candidate_id INT NOT NULL, job_offer_id INT NOT NULL, created_by_id INT NOT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C737C68891BD8781 ON job_application (candidate_id)');
        $this->addSql('CREATE INDEX IDX_C737C6883481D195 ON job_application (job_offer_id)');
        $this->addSql('CREATE INDEX IDX_C737C688B03A8386 ON job_application (created_by_id)');
        $this->addSql('CREATE INDEX IDX_C737C688896DBBDE ON job_application (updated_by_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, confirmed BOOLEAN DEFAULT false NOT NULL, confirmation_code VARCHAR(255) DEFAULT \'\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, type VARCHAR(255) NOT NULL, company_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D93D649979B1AD6 ON "user" (company_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094FB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094F896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE job ADD CONSTRAINT FK_FBD8E0F8979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE job ADD CONSTRAINT FK_FBD8E0F8B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE job ADD CONSTRAINT FK_FBD8E0F8896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE job_application ADD CONSTRAINT FK_C737C68891BD8781 FOREIGN KEY (candidate_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE job_application ADD CONSTRAINT FK_C737C6883481D195 FOREIGN KEY (job_offer_id) REFERENCES job (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE job_application ADD CONSTRAINT FK_C737C688B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE job_application ADD CONSTRAINT FK_C737C688896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE company DROP CONSTRAINT FK_4FBF094FB03A8386');
        $this->addSql('ALTER TABLE company DROP CONSTRAINT FK_4FBF094F896DBBDE');
        $this->addSql('ALTER TABLE job DROP CONSTRAINT FK_FBD8E0F8979B1AD6');
        $this->addSql('ALTER TABLE job DROP CONSTRAINT FK_FBD8E0F8B03A8386');
        $this->addSql('ALTER TABLE job DROP CONSTRAINT FK_FBD8E0F8896DBBDE');
        $this->addSql('ALTER TABLE job_application DROP CONSTRAINT FK_C737C68891BD8781');
        $this->addSql('ALTER TABLE job_application DROP CONSTRAINT FK_C737C6883481D195');
        $this->addSql('ALTER TABLE job_application DROP CONSTRAINT FK_C737C688B03A8386');
        $this->addSql('ALTER TABLE job_application DROP CONSTRAINT FK_C737C688896DBBDE');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649979B1AD6');
        $this->addSql('DROP TABLE company');
        $this->addSql('DROP TABLE job');
        $this->addSql('DROP TABLE job_application');
        $this->addSql('DROP TABLE "user"');
    }
}
